### ISSUE TITLE
Add Key Items

### ISSUE THREAD

**Issue by James-N-M** [James-N-M/faker-pokemon#2]
- Create a static array of all of at least some of the following key items
http://www.psypokes.com/rby/items.php scroll down to key items in table 
- Create a getter for new data array
- create a method to get a random value from key items getter in FakerPokemon.php
optional: create a test like the others to test the function

**Comment by vimendes** [comment]
Hi @James-N-M !
Can I contribute to this issue? :)

**Comment by azisuazusa** [comment]
@James-N-M I will work on this issue

**Comment by James-N-M** [comment]
awesome thanks ! @azisuazusa
