### ISSUE TITLE
Add function keyItem() usage to README.md Hacktoberfest good first issue

### ISSUE THREAD

**Issue by James-N-M** [James-N-M/faker-pokemon#9]
the readme.md file shows usage of the the functions available by the FakerPokemon Class
add the following line to the read me file, to showcase the use of the keyItem function

```$faker->keyItem()     // Pokedex ```

**Comment by arashemadi** [comment]
Hi @James-N-M. May I work on this, please?

**Comment by James-N-M** [comment]
somebody picked this one up ! Ill make a issue to add a contribution guideline to the readme.md so this doesnt happen again
